# Device Special configuration
TARGET_CPU_VARIANT := cortex-a73
TARGET_CPU_SMP := true
TARGET_2ND_CPU_VARIANT := cortex-a73
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_SYSTEMIMAGE_PARTITION_SIZE := 4294967296 # 4GB
BOARD_HAS_LARGE_FILESYSTEM := true
